version: '3.7'
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.5
    platform: linux/amd64

  peer0.shams.example.com:
    container_name: peer0.shams.example.com
    image: hyperledger/fabric-peer:2.5
    platform: linux/amd64

  peer0.rebar.example.com:
    container_name: peer0.rebar.example.com
    image: hyperledger/fabric-peer:2.5
    platform: linux/amd64
